server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/crud_db
    username: root
    password: 9785
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  # 타임리프 자동 읽기
  thymeleaf:
    cache: false
  # Mustache 설정
  mustache:
    charset: utf-8
    suffix: .mustache
    prefix: classpath:/templates/
    servlet:
      cache: false

#  Redis 설정 ( 추후 테스트 예정 )
#  data:
#    redis:
#      host: localhost
#      port: 6379

# Mybatis 설정
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.entvy.crud.domain
  configuration:
    map-underscore-to-camel-case: true

# 로그 레벨 설정
logging:
  level:
    root: info
    com.example.demo: debug
    com.example.demo.controller: debug
    com.example.demo.service: debug
    com.entvy.crud.mapper: debug


# 로그 파일 설정
  file:
    name: logs/app.log