spring:
  application:
    name: ch03
  datasource:
    url: jdbc:mariadb://localhost:3306/member_db
    username: root
    password: 9785
    driver-class-name: org.mariadb.jdbc.Driver
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # 타임리프 자동 읽기
  thymeleaf:
    cache: false
  # Mustache 설정
  mustache:
    charset: utf-8
    suffix: .mustache
    prefix: classpath:/templates/
    servlet:
      cache: false

#  Redis 설정 ( 추후 테스트 예정 )
#  data:
#    redis:
#      host: localhost
#      port: 6379


# 로그 레벨 설정
logging:
  level:
    root: info
    com.example.demo: debug
    com.example.demo.controller: debug
    com.example.demo.service: debug

# 로그 파일 설정
  file:
    name: logs/app.log