spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test_db
    username: test_user
    password: test_pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트마다 테이블 생성 후 삭제
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  test:
    database:
      replace: none  # Spring이 내 설정을 덮어쓰지 않게 함

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace